Repository dj-pixus/lmms-collab, pull requests merged in 2020-11, with the labels that each got.

#9 Sidechain + Mixing Changes
  midnight-sun.mmpz
  midnight-sun.mmpz.bak
Labels: Mixing, Urgent

#10 Added .gitignore
  .gitignore
  midnight-sun.mmpz.bak
Labels: Black Magic, Minor Changes

#12 Update .gitignore
  .gitignore
Labels: Black Magic, Minor Changes

#13 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Mixing, New instruments, Song Structure

#16 Fixing CamelCrusher issues and a bit more
  midnight-sun.mmpz
Labels: Instrument Edit, Mixing, Song Structure

#17 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Song Structure

#19 gitignore update
  .gitignore
Labels: Github, Minor Changes

#20 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Mixing, Song Structure

#21 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Song Structure

#22 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Minor Changes, Mixing

#23 Bup branch
  midnight-sun.mmpz
Labels: Song Structure

#26 Bup branch
  midnight-sun.mmpz
Labels: Song Structure

#27 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Mixing, Song Structure

#30 Update midnight-sun.mmpz
  midnight-sun.mmpz
Labels: Song Structure

#31 Adding Art
  art folder/midnight_sun.png
  art folder/midnight_sun.xcf
Labels: Art, Github

#32 Midnight Sun artwork update
  art folder/midnight_sun.png
  art folder/midnight_sun.xcf
Labels: Art

#33 Midnight Sun: Very last very small refinements
  art folder/midnight_sun.png
  art folder/midnight_sun.xcf
  midnight-sun.mmpz
Labels: Minor Changes
